version: "3.9"
services:
  order-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "companies-db"
      - "rabbitmq"
    networks:
      - default
    restart: on-failure:3
  companies-db:
    image: "postgres:14.2"
    ports:
      - "15432:5432"
    networks:
      - default
    hostname: companies-db
    command:
      - --max_prepared_transactions=100
    environment:
      POSTGRES_USER: user_db
      POSTGRES_DB: companies
      POSTGRES_HOST_AUTH_METHOD: trust
  rabbitmq:
    image: 'rabbitmq'
    volumes:
      - ./rabbit-mq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - "5673:5673"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 15s
      retries: 5